### ISSUE TITLE
ability to specify endpoint (for localhost)

### ISSUE THREAD

**Issue by aiqui** [shelfio/dynamodb-parallel-scan#200]
The call to `DynamoDBClient` uses the default values.  Is there a way to set the endpoint directly so that that a
local endpoint can be used?   How can a local endpoint be specified directly in the call to `parallelScan`?

https://github.com/shelfio/dynamodb-parallel-scan/blob/master/src/ddb.ts#L11-L21

**Comment by aiqui** [comment]
Forked to find solution

**Comment by vladgolubev** [comment]
feel free to open a PR with your solution and we'll get it merged!
