### ISSUE TITLE
Accept custom DynamoDB client instances

### ISSUE THREAD

**Issue by outaTiME** [shelfio/dynamodb-parallel-scan#230]
It would be nice to be able to pass as parameter an instance already configured for the DynamoDB client (it would be very useful for custom configurations like `retryStrategy`).

**Comment by jakedaleweb** [comment]
+1 I'm currently getting EMFILE (too many connection) errors in lambda with this library and I am wondering if it because it creates a new client for each command.

**Comment by jakedaleweb** [comment]
Have made a PR to address my issue https://github.com/shelfio/dynamodb-parallel-scan/pull/245

It would be trivial to then make it possible to pass in a custom dynamo client.

**Comment by vladholubiev** [comment]
fixed in 3.7.0 by https://github.com/shelfio/dynamodb-parallel-scan/pull/250
