### ISSUE TITLE
Feature request: ability to resume from failure

### ISSUE THREAD

**Issue by jakedaleweb** [shelfio/dynamodb-parallel-scan#241]
I'd like to have the ability to resume a previous scan from a particular point.

I think functionally this could be supported by returning the `LastEvaluatedKey` here (perhaps indexed by segment)
https://github.com/shelfio/dynamodb-parallel-scan/blob/master/src/parallel-scan-stream.ts#L136C31-L136C31

And then allowing the caller of `parallelScanAsStream` to provide an `ExclusiveStartKey` (again, perhaps indexed by segment) which would be passed through to the first scan.

What do you think about this? If you're open to it I could put together a pull request.

**Comment by vladgolubev** [comment]
I am all for it! However, I'd like to keep the original API unchanged, and maybe expose this functionality via a new function `parallelScanAsStreamResumable` where it will have a different arguments and response type. PRs are welcome!

**Comment by jakedaleweb** [comment]
Fantastic, will put something together when I have some time. Thanks!
